headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\aalad\\Projects\\coffee-shop-website\\out"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]